spring:
  application:
    name: Eureka-Server-2
eureka:
  instance:
    hostname: peer2
    #配置主机名
  client:
    register-with-eureka: false
    #配置服务注册中心是否以自己为客户端进行注册(配置false)
    fetch-registry: false
    #是否取得注册信息(配置false)
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8762